logo: ./logo.png
description: >
  Datascience and machine learning intro, ,,,ahdufuidshlgdfu hfdsldfhg hsdfgh dhslg dshf fdhslk gfhsufsdig jidh wehfgsid fiuhsi hdf
  dsfuvskudfhgusd nfguhufiw
  sdf hfduh;eig
  <br><br>
  <a href='https://raymondminglee.github.io'>Back to homepage</a>
theme: jekyll-theme-minimal