logo: ./logo.png
description: >
  Human/Machine interaction has become more ubiquitous to daily life. 
  People are good at focusing on a specific sound in a noisy environment, 
  however, most robots can only react to one sound at a time. This project aims to improve 
  sound localization and separation methods for robotics application, allowing robots to better  
  act to simultaneous sound sources. 

  <br><br>
  <a href='https://raymondminglee.github.io'>Back to homepage</a>
theme: jekyll-theme-minimal