logo: ./logo.png
description: >
  This project aims at improving current sound processing methods for 
  robotics applications. We proposed using microphone array and several DSP techniques 
  and could potentially allow future robot to differentiate and localize simultaneous sound sources to 
  perform better in a complex sound environment. 
  <br><br>
  <a href='https://raymondminglee.github.io'>Back to homepage</a>
theme: jekyll-theme-minimal